# Makefile template
PROJ_ROOT = ../..

include $(PROJ_ROOT)/IncludePre.mk

LIBS_CYCLING_DEPEND = 1
SUB_DIRS = 

TARGET_NAME = date
TARGET_SRCS = $(wildcard *.cpp)

DEPEND_LIBS = -lftgm

LIBS += -lpthread -ldl

include $(PROJ_ROOT)/IncludePost.mk
