#define	MAKE_BODY	1

#include "defined.h"

uint64_t	TIME_MILLISECOND				=	((uint64_t)1000UL);
uint64_t	TIME_SECOND						=	((uint64_t)1000000UL);
uint32_t	TIME_MINUTE						=	(60 * TIME_SECOND);

uint32_t	ACTIVE_OBJECT_LOOP_INTERVAL		=	(1 * TIME_MILLISECOND);

uint32_t	OBJECT_KEEP_ALIVE_INTERVAL_SEC	=	(10);
uint32_t	OBJECT_KEEP_ALIVE_INTERVAL_SEC_MIN=	(10);
uint32_t	OBJECT_KEEP_ALIVE_INTERVAL_SEC_MAX=	(60 * 60);

uint32_t	ENDPOINT_REPORT_INTERVAL		=	(10 * TIME_SECOND);
uint32_t	ENDPOINT_UPDATE_INTERVAL		=	(1 * TIME_SECOND);
uint32_t	ENDPOINT_VALUE_COUNT_MAX		=	(7*24*60);
double		ENDPOINT_VALUE_SCALE			=	(1);

int			ENDPOINT_SENSOR_TEMPERATURE_MAX	=	(100);
int			ENDPOINT_SENSOR_TEMPERATURE_MIN	=	(-20);
const char*	ENDPOINT_SENSOR_TEMPERATURE_UNIT=	"C";

uint32_t	ENDPOINT_SENSOR_HUMIDITY_MAX	= 	(100);
uint32_t	ENDPOINT_SENSOR_HUMIDITY_MIN	= 	(0);
const char*	ENDPOINT_SENSOR_HUMIDITY_UNIT	= 	"%RH";

int			SNMP_COMMUNITY_LENGTH_MAX		=	128;

