#ifndef	DEFINED_H_
#define	DEFINED_H_

#define	ID_LENGTH_MAX		32
#define	NAME_LENGTH_MAX		32
#define	IP_LENGTH_MAX		16

#define	TIME_MILLISECOND					((uint64_t)1000UL)
#define	TIME_SECOND							((uint64_t)1000000UL)
#define	TIME_MINUTE							(60 * TIME_SECOND)

#define	ACTIVE_OBJECT_LOOP_INTERVAL			(1 * TIME_MILLISECOND)

#define	OBJECT_LIVE_CHECK_INTERVAL_SEC		(60)
#define	OBJECT_LIVE_CHECK_INTERVAL_SEC_MIN	(10)
#define	OBJECT_LIVE_CHECK_INTERVAL_SEC_MAX	(60 * 60)

#define	ENDPOINT_UPDATE_INTERVAL			(10 * TIME_SECOND)
#define	ENDPOINT_VALUE_COUNT_MAX			(7*24*60)
#define	ENDPOINT_VALUE_SCALE				(1)

#define	ENDPOINT_SENSOR_TEMPERATURE_MAX		(100)
#define	ENDPOINT_SENSOR_TEMPERATURE_MIN		(-20)
#define	ENDPOINT_SENSOR_TEMPERATURE_UNIT	("C")

#define	ENDPOINT_SENSOR_HUMIDITY_MAX		(100)
#define	ENDPOINT_SENSOR_HUMIDITY_MIN		(0)
#define	ENDPOINT_SENSOR_HUMIDITY_UNIT		("%RH")

#define	DEFAULT_LOCAL_IP					"127.0.0.1"
#define	DEFAULT_SERVER_IP					"127.0.0.1"
#define	DEFAULT_SERVER_PORT					8888

#define	SNMP_COMMUNITY_LENGTH_MAX			128

#define	LOG_FILE_PATH						"/var/log/"
#define	LOG_FILE_SIZE						(1024*1024)

extern	const char *RMC_RESULT_OK;
extern	const char *RMC_RESULT_FAILED;
extern	const char *RMC_FIELD_SECTION;
extern	const char *RMC_FIELD_COMMAND;
extern	const char *RMC_FIELD_RESULT;
extern	const char *RMC_FIELD_ERROR;
extern	const char *RMC_FIELD_TYPE;
extern	const char *RMC_FIELD_DEVICE;
extern	const char *RMC_FIELD_DEVICE_ARRAY;
extern	const char *RMC_FIELD_ID;
extern	const char *RMC_FIELD_ID_ARRAY;
extern	const char *RMC_FIELD_NAME;
enum	RetValue
{
	RET_VALUE_OK,
	RET_VALUE_ERROR,
	RET_VALUE_INVALID_ARGUMENTS,
	RET_VALUE_INVALID_TYPE,
	RET_VALUE_INVALID_NAME,
};

#endif

