# Makefile template
PROJ_ROOT = ../..

include $(PROJ_ROOT)/IncludePre.mk

LIBS_CYCLING_DEPEND = 1
SUB_DIRS = 

TARGET_NAME = 
TARGET_SRCS = $(wildcard *.cpp)

DEPEND_LIBS = -lftgm

LIBS += -lpthread -lnetsnmp  -ljson /home/xtra/Workspace/KompexSQLiteWrapper-Source_1.11.14/lib/debug/KompexSQLiteWrapper_Static_d.a -ldl

include $(PROJ_ROOT)/IncludePost.mk
