# Makefile template
PROJ_ROOT = ../..

include $(PROJ_ROOT)/IncludePre.mk

LIB_NAME = ftomc_shell
LIB_SRCS = $(wildcard *.cpp) $(wildcard */*.cpp)

TARGET_NAME = 
TARGET_SRCS = 

include $(PROJ_ROOT)/IncludePost.mk
